<a href="https://colab.research.google.com/github/satyam123457/music-recomm-system/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
import Recommenders as Recommenders
import matplotlib.pyplot as plt
import seaborn as sb
import tensorflow as tf

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE
 
import warnings
warnings.filterwarnings('ignore')

#next line 
song_df_1 = pd.read_csv('triplets_file.csv')
song_df_1.head()

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995           1.0
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B           2.0
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0           1.0
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D           1.0
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273           1.0

In [8]:
song_df_2 = pd.read_csv('song_data.csv')
song_df_2.head()

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003.0
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995.0
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006.0
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003.0
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0.0

In [9]:
# combine both data
song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on='song_id', how='left')
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1.0,NaN,NaN,NaN,NaN
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2.0,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976.0
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1.0,Stronger,Graduation,Kanye West,2007.0
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1.0,NaN,NaN,NaN,NaN
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1.0,NaN,NaN,NaN,NaN

In [10]:
# creating new feature combining title and artist name
song_df['song'] = song_df['title']+' - '+song_df['artist_name']
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1.0,NaN,NaN,NaN,NaN,NaN
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2.0,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976.0,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1.0,Stronger,Graduation,Kanye West,2007.0,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1.0,NaN,NaN,NaN,NaN,NaN
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1.0,NaN,NaN,NaN,NaN,NaN

In [11]:
# taking top 10k samples for quick results
song_df = song_df.head(10000)

In [12]:
# cummulative sum of listen count of the songs
song_grouped = song_df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()

                                      song  listen_count
0                 #40 - DAVE MATTHEWS BAND             1
1  (Anaesthesia) Pulling Teath - Metallica             1
2                 14 Years - Guns N' Roses             1
3                              143 - Musiq             2
4                  16 Candles - The Crests             8

In [13]:
grouped_sum = song_grouped['listen_count'].sum()
song_grouped['percentage'] = (song_grouped['listen_count'] / grouped_sum ) * 100
song_grouped.sort_values(['listen_count', 'song'], ascending=[0,1])

,song,listen_count,percentage
1197,Undo - Björk,32,1.214421
279,Dog Days Are Over (Radio Edit) - Florence + Th...,28,1.062619
652,Lucky (Album Version) - Jason Mraz & Colbie Ca...,20,0.759013
577,Just Dance - Lady GaGa / Colby O'Donis,17,0.645161
977,Somebody To Love - Justin Bieber,17,0.645161
...,...,...,...
1315,Your Woman - White Town,1,0.037951
1316,Zero - The Pain Machinery,1,0.037951
1320,high fives - Four Tet,1,0.037951
1321,paranoid android - Christopher O'Riley,1,0.037951
1324,Época - Gotan Project,1,0.037951

In [14]:
pr = Recommenders.popularity_recommender_py()
pr.create(song_df, 'user_id', 'song')
# display the top 10 popular songs
pr.recommend(song_df['user_id'][5])

,user_id,song,score,Rank
1197,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Undo - Björk,32,1.0
279,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dog Days Are Over (Radio Edit) - Florence + Th...,28,2.0
652,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Lucky (Album Version) - Jason Mraz & Colbie Ca...,20,3.0
577,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Just Dance - Lady GaGa / Colby O'Donis,17,4.0
977,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Somebody To Love - Justin Bieber,17,5.0
174,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Bulletproof - La Roux,16,6.0
745,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Nothin' On You [feat. Bruno Mars] (Album Versi...,16,7.0
233,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Cosmic Love - Florence + The Machine,15,8.0
425,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Halo - Beyoncé,15,9.0
866,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Représente - Alliance Ethnik,15,10.0

In [15]:
ir = Recommenders.item_similarity_recommender_py()
ir.create(song_df, 'user_id', 'song')
user_items = ir.get_user_items(song_df['user_id'][5])
# display user songs history
for user_item in user_items:
    print(user_item)

nan
Entre Dos Aguas - Paco De Lucia
Stronger - Kanye West
Heaven's gonna burn your eyes - Thievery Corporation feat. Emiliana Torrini
Let It Be Sung - Jack Johnson / Matt Costa / Zach Gill / Dan Lebowitz / Steve Adams
I'll Be Missing You (Featuring Faith Evans & 112)(Album Version) - Puff Daddy
Love Shack - The B-52's
Behind The Sea [Live In Chicago] - Panic At The Disco
Oh No - Andrew Bird
Love Song For No One - John Mayer
The Middle - Jimmy Eat World
The Christmas Song  (LP Version) - King Curtis
Drive - Incubus
Right Back - Sublime

In [16]:
# give song recommendation for that user
ir.recommend(song_df['user_id'][5])

No. of unique songs for the user: 14
no. of unique songs in the training set: 1326
Non zero values in cooccurence_matrix :565

,user_id,song,score,rank
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Drunken Lullabies - Flogging Molly,0.051276,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Eye Of The Tiger - Survivor,0.049660,2
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Love Me - Justin Bieber,0.047619,3
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Here Without You - 3 Doors Down,0.047619,4
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Hide & Seek - Imogen Heap,0.036990,5
5,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Plástico - Ruben Blades,0.035714,6
6,b80344d063b5ccb3212f76538f3d9e43d87dca9e,DONTTRUSTME (Explicit Album Version) - 3OH!3,0.035714,7
7,b80344d063b5ccb3212f76538f3d9e43d87dca9e,The Warrior's Code - Dropkick Murphys,0.035714,8
8,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Rabbit Heart (Raise It Up) - Florence + The Ma...,0.034860,9
9,b80344d063b5ccb3212f76538f3d9e43d87dca9e,One Time - Justin Bieber,0.032738,10

2nd program initialise

In [20]:
spoti = pd.read_csv("genres_v2.csv", encoding='utf-8', quotechar='"')
spoti.head(3)

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,...,id,uri,track_href,analysis_url,duration_ms,time_signature,genre,song_name,Unnamed: 0,title
0,0.831,0.814,2,-7.364,1,0.4200,0.0598,0.013400,0.0556,0.3890,...,2Vc6NJ9PW9gD9q343XFRKx,spotify:track:2Vc6NJ9PW9gD9q343XFRKx,https://api.spotify.com/v1/tracks/2Vc6NJ9PW9gD...,https://api.spotify.com/v1/audio-analysis/2Vc6...,124539,4,Dark Trap,Mercury: Retrograde,NaN,NaN
1,0.719,0.493,8,-7.230,1,0.0794,0.4010,0.000000,0.1180,0.1240,...,7pgJBLVz5VmnL7uGHmRj6p,spotify:track:7pgJBLVz5VmnL7uGHmRj6p,https://api.spotify.com/v1/tracks/7pgJBLVz5Vmn...,https://api.spotify.com/v1/audio-analysis/7pgJ...,224427,4,Dark Trap,Pathology,NaN,NaN
2,0.850,0.893,5,-4.783,1,0.0623,0.0138,0.000004,0.3720,0.0391,...,0vSWgAlfpye0WCGeNmuNhy,spotify:track:0vSWgAlfpye0WCGeNmuNhy,https://api.spotify.com/v1/tracks/0vSWgAlfpye0...,https://api.spotify.com/v1/audio-analysis/0vSW...,98821,4,Dark Trap,Symbiote,NaN,NaN

In [21]:
spoti.shape

(42305, 22)

In [22]:
song_name = spoti["song_name"]
print(song_name.shape)
print(song_name.isnull().values.any())

(42305,)
True

In [23]:
song_name = song_name.values.reshape(-1,1)
song_name.shape

(42305, 1)

In [24]:
from sklearn.impute import SimpleImputer
imr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imr = imr.fit(song_name)
imputed_data = imr.transform(song_name)
song_name = pd.DataFrame(imputed_data)
song_name = song_name.rename(columns={0:"Song-Names"})
song_name.head(3)

            Song-Names
0  Mercury: Retrograde
1            Pathology
2             Symbiote

In [25]:
core = spoti[["genre","mode","duration_ms"]]
print(core.dtypes)
print(core.head())

genre          object
mode            int64
duration_ms     int64
dtype: object
       genre  mode  duration_ms
0  Dark Trap     1       124539
1  Dark Trap     1       224427
2  Dark Trap     1        98821
3  Dark Trap     1       123661
4  Dark Trap     1       123298

In [26]:
core.dtypes

genre          object
mode            int64
duration_ms     int64
dtype: object

In [27]:
core["genre"].value_counts()

Underground Rap    5875
Dark Trap          4578
Hiphop             3028
trance             2999
trap               2987
techhouse          2975
dnb                2966
psytrance          2961
techno             2956
hardstyle          2936
RnB                2099
Trap Metal         1956
Rap                1848
Emo                1680
Pop                 461
Name: genre, dtype: int64

In [28]:
core = core.replace({"genre":{"Underground Rap":0, "Dark Trap":1, "Hiphop":2, "trance":3, "trap":4, "techhouse":5, "dnb":6, "psytrance": 7, "techno":8, "hardstyle":9, "RnB":10, "Trap Metal":11, "Rap":12, "Emo":13, "Pop":14}})

In [29]:
from sklearn.decomposition import NMF
nmf = NMF(n_components = 6)
nmf_features = nmf.fit_transform(core)

In [30]:
from sklearn.preprocessing import normalize
norm_features = normalize(nmf_features)
current_music = norm_features[23,:]
similarities = norm_features.dot(current_music)
similarities

array([0.69299926, 0.94684384, 0.74815677, ..., 0.96155526, 0.94211047,
       0.92787163])

In [31]:
df = pd.DataFrame(norm_features)
x = df.join(song_name)
df = pd.pivot_table(x, x[[0,1,2,3,4,5]],["Song-Names"])#for indexing song_name to our df
def current_music(value):
    print("Top 5 recommendations for given music are:")
    value = df.loc[value]
    similarities = df.dot(value)
    print(format(similarities.nlargest()))

In [32]:
current_music("Missed Calls - Remix")

Top 5 recommendations for given music are:
Song-Names
Missed Calls - Remix        1.000000
Mobbkage                    0.999996
SEARCH & DESTRXY.           0.999977
Breakdxwn                   0.999942
Kingdom Hearts Freestyle    0.999938
dtype: float64

In [33]:
current_music("SEARCH & DESTRXY.")

Top 5 recommendations for given music are:
Song-Names
SEARCH & DESTRXY.           1.000000
Missed Calls - Remix        0.999977
Breakdxwn                   0.999964
Mobbkage                    0.999953
Kingdom Hearts Freestyle    0.999951
dtype: float64

In [36]:
current_music("Animals")

Top 5 recommendations for given music are:
Song-Names
Zim Zimma             0.964004
Call Off The Bells    0.964002
Drug$ III             0.964001
Perfect Illusion      0.964000
Hold That             0.963998
dtype: float64